export default {
    "timestamp": 1582495308326,
    "context": {
        "external_urls": {
            "spotify": "https://open.spotify.com/playlist/37i9dQZF1E35uGJbcEAo2c"
        },
        "href": "https://api.spotify.com/v1/playlists/37i9dQZF1E35uGJbcEAo2c",
        "type": "playlist",
        "uri": "spotify:playlist:37i9dQZF1E35uGJbcEAo2c"
    },
    "progress_ms": 53414,
    "item": {
        "album": {
            "album_type": "single",
            "artists": [
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/2qxJFvFYMEDqd7ui6kSAcq"
                    },
                    "href": "https://api.spotify.com/v1/artists/2qxJFvFYMEDqd7ui6kSAcq",
                    "id": "2qxJFvFYMEDqd7ui6kSAcq",
                    "name": "Zedd",
                    "type": "artist",
                    "uri": "spotify:artist:2qxJFvFYMEDqd7ui6kSAcq"
                },
                {
                    "external_urls": {
                        "spotify": "https://open.spotify.com/artist/2wUjUUtkb5lvLKcGKsKqsR"
                    },
                    "href": "https://api.spotify.com/v1/artists/2wUjUUtkb5lvLKcGKsKqsR",
                    "id": "2wUjUUtkb5lvLKcGKsKqsR",
                    "name": "Alessia Cara",
                    "type": "artist",
                    "uri": "spotify:artist:2wUjUUtkb5lvLKcGKsKqsR"
                }
            ],
            "available_markets": [
                "AD",
                "AE",
                "AR",
                "AT",
                "AU",
                "BE",
                "BG",
                "BH",
                "BO",
                "BR",
                "CA",
                "CH",
                "CL",
                "CO",
                "CR",
                "CY",
                "CZ",
                "DE",
                "DK",
                "DO",
                "DZ",
                "EC",
                "EE",
                "EG",
                "ES",
                "FI",
                "FR",
                "GB",
                "GR",
                "GT",
                "HK",
                "HN",
                "HU",
                "ID",
                "IE",
                "IL",
                "IN",
                "IS",
                "IT",
                "JO",
                "JP",
                "KW",
                "LB",
                "LI",
                "LT",
                "LU",
                "LV",
                "MA",
                "MC",
                "MT",
                "MX",
                "MY",
                "NI",
                "NL",
                "NO",
                "NZ",
                "OM",
                "PA",
                "PE",
                "PH",
                "PL",
                "PS",
                "PT",
                "PY",
                "QA",
                "RO",
                "SA",
                "SE",
                "SG",
                "SK",
                "SV",
                "TH",
                "TN",
                "TR",
                "TW",
                "US",
                "UY",
                "VN",
                "ZA"
            ],
            "external_urls": {
                "spotify": "https://open.spotify.com/album/1I4W7JKzYbl8VKRfD61DIS"
            },
            "href": "https://api.spotify.com/v1/albums/1I4W7JKzYbl8VKRfD61DIS",
            "id": "1I4W7JKzYbl8VKRfD61DIS",
            "images": [
                {
                    "height": 640,
                    "url": "https://i.scdn.co/image/b198cc1e6a301d337b814036baeca0d5c648e12d",
                    "width": 640
                },
                {
                    "height": 300,
                    "url": "https://i.scdn.co/image/55d5325965a491b200a310de8695919166cfb056",
                    "width": 300
                },
                {
                    "height": 64,
                    "url": "https://i.scdn.co/image/5d87902197a337ff5755fea984ff4d28c2c91126",
                    "width": 64
                }
            ],
            "name": "This is a long song title",
            "release_date": "2017-02-23",
            "release_date_precision": "day",
            "total_tracks": 1,
            "type": "album",
            "uri": "spotify:album:1I4W7JKzYbl8VKRfD61DIS"
        },
        "artists": [
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/2qxJFvFYMEDqd7ui6kSAcq"
                },
                "href": "https://api.spotify.com/v1/artists/2qxJFvFYMEDqd7ui6kSAcq",
                "id": "2qxJFvFYMEDqd7ui6kSAcq",
                "name": "Zedd",
                "type": "artist",
                "uri": "spotify:artist:2qxJFvFYMEDqd7ui6kSAcq"
            },
            {
                "external_urls": {
                    "spotify": "https://open.spotify.com/artist/2wUjUUtkb5lvLKcGKsKqsR"
                },
                "href": "https://api.spotify.com/v1/artists/2wUjUUtkb5lvLKcGKsKqsR",
                "id": "2wUjUUtkb5lvLKcGKsKqsR",
                "name": "Alessia Cara",
                "type": "artist",
                "uri": "spotify:artist:2wUjUUtkb5lvLKcGKsKqsR"
            }
        ],
        "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 210090,
        "explicit": false,
        "external_ids": {
            "isrc": "USUM71700736"
        },
        "external_urls": {
            "spotify": "https://open.spotify.com/track/6uBhi9gBXWjanegOb2Phh0"
        },
        "href": "https://api.spotify.com/v1/tracks/6uBhi9gBXWjanegOb2Phh0",
        "id": "6uBhi9gBXWjanegOb2Phh0",
        "is_local": false,
        "name": "Stay",
        "popularity": 77,
        "preview_url": "https://p.scdn.co/mp3-preview/3f794acc211c14f5bbaef6ff44aa57b02b69bd9d?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:6uBhi9gBXWjanegOb2Phh0"
    },
    "currently_playing_type": "track",
    "actions": {
        "disallows": {
            "resuming": true
        }
    },
    "is_playing": true
};
